/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.etec.chamada;

import br.gov.sp.etec.dao.LoginDAO;
import br.gov.sp.etec.dao.UtilDAO;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Edson
 */
public class ChamadaGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChamadaGUI
     */
    public ChamadaGUI() {
        initComponents();
        this.populaComboBox2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNome1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldNome2 = new javax.swing.JTextField();
        jTextFieldNome3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldNome4 = new javax.swing.JTextField();
        jTextFieldNome5 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldNome6 = new javax.swing.JTextField();
        jComboBox6_escolha_turma = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jRadioButtonPresente1 = new javax.swing.JRadioButton();
        jRadioButtonAsuente1 = new javax.swing.JRadioButton();
        jComboBoxSentimento1 = new javax.swing.JComboBox<>();
        jRadioButtonAsuente2 = new javax.swing.JRadioButton();
        jRadioButtonPresente2 = new javax.swing.JRadioButton();
        jComboBoxSentimento2 = new javax.swing.JComboBox<>();
        jComboBoxSentimento3 = new javax.swing.JComboBox<>();
        jRadioButtonAsuente3 = new javax.swing.JRadioButton();
        jRadioButtonPresente3 = new javax.swing.JRadioButton();
        jComboBoxSentimento4 = new javax.swing.JComboBox<>();
        jRadioButtonAsuente4 = new javax.swing.JRadioButton();
        jRadioButtonPresente4 = new javax.swing.JRadioButton();
        jComboBoxSentimento5 = new javax.swing.JComboBox<>();
        jRadioButtonAsuente5 = new javax.swing.JRadioButton();
        jRadioButtonPresente5 = new javax.swing.JRadioButton();
        jComboBoxSentimento6 = new javax.swing.JComboBox<>();
        jRadioButtonAsuente6 = new javax.swing.JRadioButton();
        jRadioButtonPresente6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chamada");

        jTextFieldNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNome1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Nome:");

        jLabel19.setText("Nome:");

        jTextFieldNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNome2ActionPerformed(evt);
            }
        });

        jTextFieldNome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNome3ActionPerformed(evt);
            }
        });

        jLabel21.setText("Nome:");

        jLabel23.setText("Nome:");

        jTextFieldNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNome4ActionPerformed(evt);
            }
        });

        jTextFieldNome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNome5ActionPerformed(evt);
            }
        });

        jLabel25.setText("Nome:");

        jLabel27.setText("Nome:");

        jTextFieldNome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNome6ActionPerformed(evt);
            }
        });

        jComboBox6_escolha_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6_escolha_turmaActionPerformed(evt);
            }
        });

        jLabel10.setText("Escolha a turma:");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Gravar chamada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPresente1);
        jRadioButtonPresente1.setText("Prensente");

        buttonGroup1.add(jRadioButtonAsuente1);
        jRadioButtonAsuente1.setText("Ausente");
        jRadioButtonAsuente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAsuente1ActionPerformed(evt);
            }
        });

        jComboBoxSentimento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Animado", "Mais ou menos", "Desanimado" }));

        buttonGroup2.add(jRadioButtonAsuente2);
        jRadioButtonAsuente2.setText("Ausente");
        jRadioButtonAsuente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAsuente2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonPresente2);
        jRadioButtonPresente2.setText("Prensente");

        jComboBoxSentimento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Animado", "Mais ou menos", "Desanimado" }));

        jComboBoxSentimento3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Animado", "Mais ou menos", "Desanimado" }));

        buttonGroup3.add(jRadioButtonAsuente3);
        jRadioButtonAsuente3.setText("Ausente");
        jRadioButtonAsuente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAsuente3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonPresente3);
        jRadioButtonPresente3.setText("Prensente");

        jComboBoxSentimento4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Animado", "Mais ou menos", "Desanimado" }));

        buttonGroup4.add(jRadioButtonAsuente4);
        jRadioButtonAsuente4.setText("Ausente");
        jRadioButtonAsuente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAsuente4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButtonPresente4);
        jRadioButtonPresente4.setText("Prensente");

        jComboBoxSentimento5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Animado", "Mais ou menos", "Desanimado" }));

        buttonGroup5.add(jRadioButtonAsuente5);
        jRadioButtonAsuente5.setText("Ausente");
        jRadioButtonAsuente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAsuente5ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButtonPresente5);
        jRadioButtonPresente5.setText("Prensente");

        jComboBoxSentimento6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Animado", "Mais ou menos", "Desanimado" }));

        buttonGroup6.add(jRadioButtonAsuente6);
        jRadioButtonAsuente6.setText("Ausente");
        jRadioButtonAsuente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAsuente6ActionPerformed(evt);
            }
        });

        buttonGroup6.add(jRadioButtonPresente6);
        jRadioButtonPresente6.setText("Prensente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome6, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonPresente6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAsuente6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSentimento6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonPresente5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAsuente5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSentimento5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonPresente4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAsuente4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSentimento4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonPresente3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAsuente3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSentimento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonPresente2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAsuente2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSentimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonPresente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAsuente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSentimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox6_escolha_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(238, 238, 238))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox6_escolha_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonPresente1)
                        .addComponent(jRadioButtonAsuente1)
                        .addComponent(jComboBoxSentimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonPresente2)
                        .addComponent(jRadioButtonAsuente2)
                        .addComponent(jComboBoxSentimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jRadioButtonPresente3)
                        .addComponent(jRadioButtonAsuente3)
                        .addComponent(jComboBoxSentimento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldNome3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jRadioButtonPresente4)
                        .addComponent(jRadioButtonAsuente4)
                        .addComponent(jComboBoxSentimento4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldNome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonPresente5)
                    .addComponent(jRadioButtonAsuente5)
                    .addComponent(jComboBoxSentimento5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jRadioButtonPresente6)
                    .addComponent(jRadioButtonAsuente6)
                    .addComponent(jComboBoxSentimento6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNome1ActionPerformed

    private void jTextFieldNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNome2ActionPerformed

    private void jTextFieldNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNome3ActionPerformed

    private void jTextFieldNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNome4ActionPerformed

    private void jTextFieldNome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNome5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNome5ActionPerformed

    private void jTextFieldNome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNome6ActionPerformed

    private void jComboBox6_escolha_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6_escolha_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6_escolha_turmaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        //        Calendar cal = new GregorianCalendar();
        //        System.out.println(cal);
        //        int min = cal.getMinimum(DAY_OF_MONTH); //Retorna o primeiro dia
        //        int maximum = cal.getMaximum(DAY_OF_MONTH);
        //Retorna o último dia
        Chamada c = new Chamada();
        String nomeTurma = String.valueOf(jComboBox6_escolha_turma.getSelectedItem());
        c.setNomeTurma(nomeTurma);
        populaTextField(c);
        jTextFieldNome1.setText(c.getNomeAluno1());
        jTextFieldNome2.setText(c.getNomeAluno2());
        jTextFieldNome3.setText(c.getNomeAluno3());
        jTextFieldNome4.setText(c.getNomeAluno4());
        jTextFieldNome5.setText(c.getNomeAluno5());
        jTextFieldNome6.setText(c.getNomeAluno6());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonAsuente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAsuente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAsuente1ActionPerformed

    private void jRadioButtonAsuente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAsuente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAsuente2ActionPerformed

    private void jRadioButtonAsuente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAsuente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAsuente3ActionPerformed

    private void jRadioButtonAsuente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAsuente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAsuente4ActionPerformed

    private void jRadioButtonAsuente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAsuente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAsuente5ActionPerformed

    private void jRadioButtonAsuente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAsuente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAsuente6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Chamada c = new Chamada();
        ChamadaDAO dao = new ChamadaDAO();
        Date data = new Date();
        DateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
        String dataFormatada = formatter.format(data);
        String nome, nomeTurma, status, obs;
        boolean presenca = false;
        int cont = 0;
        while (cont <= 7) {

            if (cont == 1) {
                nome = jTextFieldNome1.getText();
                if (nome.equals("")) {
                } else {
                    nomeTurma = jComboBox6_escolha_turma.getSelectedItem().toString();
                    status = jComboBoxSentimento1.getSelectedItem().toString();
                    obs = "Teste";
                    if (jRadioButtonPresente1.isSelected()) {
                        presenca = true;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonAsuente1.isSelected()) {
                        presenca = false;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonPresente1.isSelected() || jRadioButtonAsuente1.isSelected()) {
                        JOptionPane.showMessageDialog(null, "O primeiro aluno  não e onípresente...");
                    }
                    c.setData_chamada(dataFormatada);
                    c.setNome(nome);
                    c.setNomeTurma(nomeTurma);
                    c.setStatus(status);
                    c.setObservacao(obs);
                    dao.insertChamada(c);
                }
            }

            //
            if (cont == 2) {
                nome = jTextFieldNome2.getText();
                if (nome.equals("")) {
                } else {
                    nomeTurma = jComboBox6_escolha_turma.getSelectedItem().toString();
                    status = jComboBoxSentimento2.getSelectedItem().toString();
                    obs = "Teste";
                    if (jRadioButtonPresente2.isSelected()) {
                        presenca = true;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonAsuente2.isSelected()) {
                        presenca = false;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonPresente2.isSelected() || jRadioButtonAsuente2.isSelected()) {
                        JOptionPane.showMessageDialog(null, "O segundo aluno  não e onípresente...");
                    }
                    c.setData_chamada(dataFormatada);
                    c.setNome(nome);
                    c.setNomeTurma(nomeTurma);
                    c.setStatus(status);
                    c.setObservacao(obs);
                    dao.insertChamada(c);
                }
            }
            //
            if (cont == 3) {
                nome = jTextFieldNome3.getText();
                if (nome.equals("")) {
                } else {
                    nomeTurma = jComboBox6_escolha_turma.getSelectedItem().toString();
                    status = jComboBoxSentimento3.getSelectedItem().toString();
                    obs = "Teste";
                    if (jRadioButtonPresente3.isSelected()) {
                        presenca = true;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonAsuente3.isSelected()) {
                        presenca = false;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonPresente3.isSelected() || jRadioButtonAsuente3.isSelected()) {
                        JOptionPane.showMessageDialog(null, "O terceiro aluno  não e onípresente...");
                    }
                    c.setData_chamada(dataFormatada);
                    c.setNome(nome);
                    c.setNomeTurma(nomeTurma);
                    c.setStatus(status);
                    c.setObservacao(obs);
                    dao.insertChamada(c);
                }
            }
            if (cont == 4) {
                nome = jTextFieldNome4.getText();
                if (nome.equals("")) {
                } else {
                    nomeTurma = jComboBox6_escolha_turma.getSelectedItem().toString();
                    status = jComboBoxSentimento4.getSelectedItem().toString();
                    obs = "Teste";
                    if (jRadioButtonPresente4.isSelected()) {
                        presenca = true;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonAsuente4.isSelected()) {
                        presenca = false;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonPresente4.isSelected() || jRadioButtonAsuente4.isSelected()) {
                        JOptionPane.showMessageDialog(null, "O quarto aluno  não e onípresente...");
                    }
                    c.setData_chamada(dataFormatada);
                    c.setNome(nome);
                    c.setNomeTurma(nomeTurma);
                    c.setStatus(status);
                    c.setObservacao(obs);
                    dao.insertChamada(c);
                }
            }
            if (cont == 5) {
                nome = jTextFieldNome5.getText();
                if (nome.equals("")) {
                } else {
                    nomeTurma = jComboBox6_escolha_turma.getSelectedItem().toString();
                    status = jComboBoxSentimento5.getSelectedItem().toString();
                    obs = "Teste";
                    if (jRadioButtonPresente5.isSelected()) {
                        presenca = true;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonAsuente5.isSelected()) {
                        presenca = false;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonPresente5.isSelected() || jRadioButtonAsuente5.isSelected()) {
                        JOptionPane.showMessageDialog(null, "O primeiro aluno  não e onípresente...");
                    }
                    c.setData_chamada(dataFormatada);
                    c.setNome(nome);
                    c.setNomeTurma(nomeTurma);
                    c.setStatus(status);
                    c.setObservacao(obs);
                    dao.insertChamada(c);
                }
            }
            if (cont == 6) {
                nome = jTextFieldNome6.getText();
                if (nome.equals("")) {
                } else {
                    nomeTurma = jComboBox6_escolha_turma.getSelectedItem().toString();
                    status = jComboBoxSentimento6.getSelectedItem().toString();
                    obs = "Teste";
                    if (jRadioButtonPresente6.isSelected()) {
                        presenca = true;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonAsuente6.isSelected()) {
                        presenca = false;
                        c.setPrensenca(presenca);
                    } else if (jRadioButtonPresente6.isSelected() || jRadioButtonAsuente6.isSelected()) {
                        JOptionPane.showMessageDialog(null, "O primeiro aluno  não e onípresente...");
                    }
                    c.setData_chamada(dataFormatada);
                    c.setNome(nome);
                    c.setNomeTurma(nomeTurma);
                    c.setStatus(status);
                    c.setObservacao(obs);
                    dao.insertChamada(c);
                }
            }
            cont++;
        }
        JOptionPane.showMessageDialog(null, "Dados salvos.");
        jComboBox6_escolha_turma.removeAllItems();
        this.populaComboBox2();

    }//GEN-LAST:event_jButton1ActionPerformed

    public void populaComboBox2() {
       Date data = new Date();
        DateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
       String  dataFormatada = formatter.format(data);
        String sql = "select DISTINCT div_turma.nome_turma from div_turma\n" +
"	inner join cadastro_prof on (div_turma.fk_prof_rp = cadastro_prof.rp)\n" +
" where not exists \n" +
"	(select chamada.nome_turma from chamada where  div_turma.nome_turma = chamada.nome_turma and chamada.data_chamada= ?);";
        try {
            Connection con = null;
            con = UtilDAO.conectar();
            PreparedStatement stm = null;
            stm = con.prepareStatement(sql);
            stm.setString(1, dataFormatada);
            ResultSet rs = stm.executeQuery();

            while (rs.next()) {
                jComboBox6_escolha_turma.addItem(rs.getString("NOME_TURMA"));
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }


    }

    public Chamada populaTextField(Chamada c) {
        String sql = "SELECT DISTINCT * FROM DIV_TURMA INNER JOIN CADASTRO_PROF ON (DIV_TURMA.FK_PROF_RP = CADASTRO_PROF.RP) \n"
                + "                        INNER JOIN CAD_ALUNO ON (DIV_TURMA.FK_ALUNO_RA = CAD_ALUNO.RA) WHERE DIV_TURMA.NOME_TURMA = ?";
        try {
            Connection con = null;
            con = UtilDAO.conectar();
            PreparedStatement stm = null;
            stm = con.prepareStatement(sql);
            String nomeTurma = c.getNomeTurma();
            System.out.println(nomeTurma);
            stm.setString(1, c.getNomeTurma());
            ResultSet rs = stm.executeQuery();
            

                if (rs.next()) {
                    c.setNomeAluno1(rs.getString("CAD_ALUNO.NOME"));
                }
                
                if (/*rs.previous() !=*/rs.next()) {

                    c.setNomeAluno2(rs.getString("CAD_ALUNO.NOME"));
                }
                if (rs.next()) {

                    c.setNomeAluno3(rs.getString("CAD_ALUNO.NOME"));
                }
                if (/*rs.previous() !=*/rs.next()) {

                    c.setNomeAluno4(rs.getString("CAD_ALUNO.NOME"));
                }
                if (rs.next()) {

                    c.setNomeAluno5(rs.getString("CAD_ALUNO.NOME"));
                }
                if ( /*rs.previous() !=*/rs.next()) {

                    c.setNomeAluno6(rs.getString("CAD_ALUNO.NOME"));
                }

            

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return c;
    }

    public List<Chamada> selectAlunos(Chamada c) {
        Connection con = UtilDAO.conectar();
        List<Chamada> listaAlunos = new ArrayList<>();
        try {
            PreparedStatement ps = null;
            String sql = "SELECT DISTINCT cad_aluno.nome as nomeAluno FROM DIV_TURMA INNER JOIN CADASTRO_PROF ON (DIV_TURMA.FK_PROF_RP = CADASTRO_PROF.RP) \n"
                    + "                        INNER JOIN CAD_ALUNO ON (DIV_TURMA.FK_ALUNO_RA = CAD_ALUNO.RA) WHERE DIV_TURMA.NOME_TURMA = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, c.getNomeTurma());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                c.setNome(rs.getString("nomeAluno"));

                listaAlunos.add(c);

            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar buscar a conta");
            ex.printStackTrace();
        }
        return listaAlunos;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamadaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox6_escolha_turma;
    private javax.swing.JComboBox<String> jComboBoxSentimento1;
    private javax.swing.JComboBox<String> jComboBoxSentimento2;
    private javax.swing.JComboBox<String> jComboBoxSentimento3;
    private javax.swing.JComboBox<String> jComboBoxSentimento4;
    private javax.swing.JComboBox<String> jComboBoxSentimento5;
    private javax.swing.JComboBox<String> jComboBoxSentimento6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAsuente1;
    private javax.swing.JRadioButton jRadioButtonAsuente2;
    private javax.swing.JRadioButton jRadioButtonAsuente3;
    private javax.swing.JRadioButton jRadioButtonAsuente4;
    private javax.swing.JRadioButton jRadioButtonAsuente5;
    private javax.swing.JRadioButton jRadioButtonAsuente6;
    private javax.swing.JRadioButton jRadioButtonPresente1;
    private javax.swing.JRadioButton jRadioButtonPresente2;
    private javax.swing.JRadioButton jRadioButtonPresente3;
    private javax.swing.JRadioButton jRadioButtonPresente4;
    private javax.swing.JRadioButton jRadioButtonPresente5;
    private javax.swing.JRadioButton jRadioButtonPresente6;
    private javax.swing.JTextField jTextFieldNome1;
    private javax.swing.JTextField jTextFieldNome2;
    private javax.swing.JTextField jTextFieldNome3;
    private javax.swing.JTextField jTextFieldNome4;
    private javax.swing.JTextField jTextFieldNome5;
    private javax.swing.JTextField jTextFieldNome6;
    // End of variables declaration//GEN-END:variables
}
