/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.etec.chamada;

import br.gov.sp.etec.dao.UtilDAO;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edson
 */
public class ListarFreq extends javax.swing.JFrame {
    String nomeTurma = "";
    String dataFormatada = "";
    String dataFormatada2 = "";
    /**
     * Creates new form ListarFreq
     */
    public ListarFreq() {
        initComponents();
        this.populaComboBox2();
        jPanel1.add(getJScrollPaneDados());
    }
    
    private JScrollPane jScrollPaneDados;
    private JTable jTableDados;
    private ChamadaDAO cdao = new ChamadaDAO();


	private JScrollPane getJScrollPaneDados() {
        if (jScrollPaneDados == null) {
            jScrollPaneDados = new JScrollPane();
            //new Rectangle(x, y, width, height)
            // x=Horizontal, y=Vertical, width=largura, height=altura
            jScrollPaneDados.setBounds(new Rectangle(1, 60, 400, 400));
            jScrollPaneDados.setViewportView(getJTableDados());
        }
        return jScrollPaneDados;
    }

    private JTable getJTableDados() {
        if (jTableDados == null) {
            try {
                String[] colunas = new String[]{"Nome do aluno", "Frequêcia"};
                DefaultTableModel dt = new DefaultTableModel(new String[][]{}, colunas);
                jTableDados = new JTable(dt);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao obter lista de contatos");
                e.printStackTrace();
            }

        }
        return jTableDados;
    }
    
    private DefaultTableModel getTableModel(){
        return (DefaultTableModel) jTableDados.getModel();
    }
////    private void preenche(Chamada c){
//        DefaultTableModel dt2 = (DefaultTableModel) jTableDados.getModel();
//        String[] dados = new String[4];
//        dados[0] = String.valueOf(c.getId());
//        dados[1] = c.getNome();
//        dados[2] = c.getTel();
//        dados[3] = c.getEmail();
//        dt2.addRow(dados);
//    }
//    private void removeTodasLinhas(){
//        int length = jTableDados.getRowCount();
//        for (int i = length - 1; i >= 0 ;i--) {
//            removeIndice(i);
//        }
//    }
//    private void removeSelecionado(){
//        int linha =jTableDados.getSelectedRow();
//        removeIndice(linha);
//    }
//    private void removeIndice(int indice){
//        DefaultTableModel dt2 = getTableModel();
//        dt2.removeRow(indice);
//    }
//    private void novaLinha(){
//        Contato c = new Contato();
//        preenche(c);
//    }
//    private Contato getLinha(){
//        int linha = jTableDados.getSelectedRow();
//        Contato contatos = new Contato();
//        DefaultTableModel dt2 = (DefaultTableModel) jTableDados.getModel();
//        
//        String id = dt2.getValueAt(linha, 0).toString();
//        String nome = dt2.getValueAt(linha, 1).toString();
//        String tel = dt2.getValueAt(linha, 2).toString();
//        String email = dt2.getValueAt(linha, 3).toString();
//        
//        
//        contatos.setId(Integer.parseInt(id));
//        contatos.setNome(nome.trim());
//        contatos.setTel(tel.trim());
//        contatos.setEmail(email.trim());
//        
//        return contatos;
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBox6_escolha_turma = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxMeia = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Frequência");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox6_escolha_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6_escolha_turmaActionPerformed(evt);
            }
        });

        jLabel10.setText("Escolha a turma:");

        jCheckBoxMeia.setText("1/2");
        jCheckBoxMeia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCheckBoxMeiaFocusLost(evt);
            }
        });
        jCheckBoxMeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMeiaActionPerformed(evt);
            }
        });

        jLabel1.setText("Turma:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxMeia)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox6_escolha_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox6_escolha_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jCheckBoxMeia)
                    .addComponent(jLabel1))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Chamada c = new Chamada();
        Date data = new Date();
        Date data2 = new Date();
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = Calendar.getInstance();
        c1.setTime(data);
        c2.setTime(data2);
        c1.add(Calendar.MONTH, 0);
        c2.add(Calendar.MONTH, 0);
        c1.set(Calendar.DAY_OF_MONTH, c1.getActualMinimum(Calendar.DAY_OF_MONTH));
        c2.set(Calendar.DAY_OF_MONTH, c1.getActualMaximum(Calendar.DAY_OF_MONTH));
        DateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
        dataFormatada = formatter.format(c1.getTime());
        dataFormatada2 = formatter.format(c2.getTime());
        
        System.out.println(dataFormatada);
        System.out.println(dataFormatada2);
        
        nomeTurma = jComboBox6_escolha_turma.getSelectedItem().toString();
        c.setNomeTurma(nomeTurma);
        String perct = "%";
        
        if(jCheckBoxMeia.isSelected()){
            DefaultTableModel modelo = (DefaultTableModel) jTableDados.getModel();
        modelo.setNumRows(0);
      for(Chamada c3 : selectFrequencia2()){
            modelo.addRow(new Object[]{
                c3.getNome(),
                c3.getFrequencia()+perct
                
            });}
        }else{
             DefaultTableModel modelo = (DefaultTableModel) jTableDados.getModel();
        modelo.setNumRows(0);
      for(Chamada c3 : selectFrequencia()){
            modelo.addRow(new Object[]{
                c3.getNome(),
                c3.getFrequencia()+perct
                
            });}
        }
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox6_escolha_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6_escolha_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6_escolha_turmaActionPerformed

    private void jCheckBoxMeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMeiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMeiaActionPerformed

    private void jCheckBoxMeiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCheckBoxMeiaFocusLost
    
        if(jCheckBoxMeia.isSelected()){
        populaComboBoxMeia();
        } else{
            populaComboBox2();
        }
    }//GEN-LAST:event_jCheckBoxMeiaFocusLost
    
      public List<Chamada> selectFrequencia(){
		Connection con = UtilDAO.conectar();
                List<Chamada> listar= new ArrayList<>();
		try {
			PreparedStatement ps = null;
			String sql = "select chamada.nome_aluno as nome, sum(chamada.presenca) * 100/ 4 as pres from chamada where chamada.nome_turma = ? and chamada.data_chamada between ? and ? group by chamada.nome_aluno";
			ps = con.prepareStatement(sql);
                        ps.setString(1, nomeTurma);
                        ps.setString(2, dataFormatada);
                        ps.setString(3, dataFormatada2);
			ResultSet rs = ps.executeQuery();

			while(rs.next()) {
                            
                                Chamada c = new Chamada();
                                c.setNome(rs.getString("nome"));
                                c.setFrequencia(rs.getDouble("pres"));
				listar.add(c);
				
			}
			rs.close();
			ps.close();
			con.close();
		} catch (SQLException ex) {
			                 JOptionPane.showMessageDialog(null, "Erro ao tentar buscar os valores");
			ex.printStackTrace();
		}
		return listar;
	}
      
      public List<Chamada> selectFrequencia2(){
		Connection con = UtilDAO.conectar();
                List<Chamada> listar= new ArrayList<>();
		try {
			PreparedStatement ps = null;
			String sql = "select chamada.nome_aluno as nome, sum((chamada.presenca) * 100/ 4) / 2 as pres from chamada where chamada.nome_turma = ? and chamada.data_chamada between ? and ? group by chamada.nome_aluno";
			ps = con.prepareStatement(sql);
                        ps.setString(1, nomeTurma);
                        ps.setString(2, dataFormatada);
                        ps.setString(3, dataFormatada2);
			ResultSet rs = ps.executeQuery();

			while(rs.next()) {
                            
                                Chamada c = new Chamada();
                                c.setNome(rs.getString("nome"));
                                c.setFrequencia(rs.getDouble("pres"));
				listar.add(c);
				
			}
			rs.close();
			ps.close();
			con.close();
		} catch (SQLException ex) {
			                 JOptionPane.showMessageDialog(null, "Erro ao tentar buscar os valores");
			ex.printStackTrace();
		}
		return listar;
	}
    
     public void populaComboBox2(){        
        String sql = "select DISTINCT div_turma.nome_turma from div_turma\n" +
" where div_turma.SegundoDia_Semana is null ORDER BY NOME_TURMA;";
        try{
            Connection con = null;      
            con = UtilDAO.conectar();
            PreparedStatement stm = null;
            stm = con.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            jComboBox6_escolha_turma.removeAllItems();
            while(rs.next()){
                jComboBox6_escolha_turma.addItem(rs.getString("NOME_TURMA"));
            }

        }catch(SQLException ex){ 
            ex.printStackTrace();
        }
        
    }
     public void populaComboBoxMeia(){        
        String sql = "select DISTINCT div_turma.nome_turma from div_turma\n" +
" where div_turma.SegundoDia_Semana is not null ORDER BY NOME_TURMA;";
        try{
            Connection con = null;      
            con = UtilDAO.conectar();
            PreparedStatement stm = null;
            stm = con.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
           jComboBox6_escolha_turma.removeAllItems();
            while(rs.next()){
                jComboBox6_escolha_turma.addItem(rs.getString("NOME_TURMA"));
            }

        }catch(SQLException ex){ 
            ex.printStackTrace();
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarFreq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxMeia;
    private javax.swing.JComboBox<String> jComboBox6_escolha_turma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
