/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Div_turmas.classes.gui;

import Div_turmas.classes.dao.DivTurmasDAO;
import Div_turmas.classes.modelagem.DivTurmas;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Rocha
 */
public class CriarTurmaGUI extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form CriarTurmaGUI
     */
    public CriarTurmaGUI() {
        initComponents();
        /*buttonGroup1
        jRadioButtonNao
        jRadioButtonSim
*/
        buttonGroup1.add(jRadioButtonSim);
        buttonGroup1.add(jRadioButtonNao);
        jRadioButtonNao.setSelected(true);
        
        
        jComboBoxSegundoDiaSemana.setEnabled(false);
        jTextField2SegundoHorarioSemana.setEnabled(false);

        
        
    }
    
        
        
    /*VARIAVEIS GLOBAIS DO CODIGO*/
    String CriaTurmaClass_dia_semana;
    String CriarTurmaClass_horario;
    String CriarTurmaClass_modalidade;
    /*MAIS OUTRAS TRES VARIAVEIS DO CODIGO*/
    String CriaTurmaClassSegundo_dia_semana, CriarTurmaClassSegundo_horario;
     
    
    public DivTurmas lerPaginaCriaTurma(){
     
        DivTurmas dt = new DivTurmas();
        DivTurmasDAO dao  = new DivTurmasDAO();
        
        String nome = jTextField1Nome_turma.getText();
        dt.setNome_turma(nome);
        
        String dia = jComboBox1_Dia_semana.getSelectedItem().toString();
        dt.setDia_semana(dia);
        
        if(jComboBox2_horario != null){
            
            String horario2 = jComboBox2_horario.getSelectedItem().toString();
           
            try {
                dt.setHorario_dia(dt.formatarHora(horario2));
                
            } catch (ParseException ex) {
                Logger.getLogger(CriarTurmaGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Há algo de errado com a conversao de String para hora. (1)");

            }
            
        }else if(jTextField2_horario != null){
            
            String horario = jTextField2_horario.getText();
            try {
                dt.setHorario_dia(dt.formatarHora(horario));
            } catch (ParseException ex) {
                Logger.getLogger(CriarTurmaGUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Há algo de errado com a conversao de String para hora. (2)");
            }
            
        }else{
        JOptionPane.showMessageDialog(null, "Escolha um horario.");
        
        }
        
        
        
        
        String modalidade = jComboBox3_modalidade.getSelectedItem().toString();
        dt.setModalidade(modalidade);
        
        return null;

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1Nome_turma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1_Dia_semana = new javax.swing.JComboBox<>();
        jComboBox2_horario = new javax.swing.JComboBox<>();
        jTextField2_horario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3_modalidade = new javax.swing.JComboBox<>();
        jButton1_criar_turma = new javax.swing.JButton();
        jButton2_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButtonNao = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxSegundoDiaSemana = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField2SegundoHorarioSemana = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Criação de turmas");

        jLabel1.setText("Nome da turma");

        jTextField1Nome_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1Nome_turmaActionPerformed(evt);
            }
        });

        jLabel2.setText("Dia da semana");

        jLabel3.setText("Horario da turma");

        jLabel4.setText("Modalidade ");

        jComboBox1_Dia_semana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado", " ", " " }));
        jComboBox1_Dia_semana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_Dia_semanaActionPerformed(evt);
            }
        });

        jComboBox2_horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00" }));
        jComboBox2_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_horarioActionPerformed(evt);
            }
        });

        jTextField2_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_horarioActionPerformed(evt);
            }
        });

        jLabel5.setText("ou");

        jComboBox3_modalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inglês Básico", "Inglês Intermediário", "Inglês Avançado", "Inglês para Viagem", "Inglês para Conversação" }));
        jComboBox3_modalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3_modalidadeActionPerformed(evt);
            }
        });

        jButton1_criar_turma.setText("Criar turma");
        jButton1_criar_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_criar_turmaActionPerformed(evt);
            }
        });

        jButton2_cancelar.setText("Cancelar");
        jButton2_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_cancelarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("Esta turma será de duas aulas na semana com duração de 1 hora cada?");

        jRadioButtonSim.setText("Sim");
        jRadioButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSimActionPerformed(evt);
            }
        });

        jRadioButtonNao.setText("Não");
        jRadioButtonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNaoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("Segundo dia da semana");

        jComboBoxSegundoDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado" }));
        jComboBoxSegundoDiaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSegundoDiaSemanaActionPerformed(evt);
            }
        });

        jLabel8.setText("Segundo horário da turma");

        jTextField2SegundoHorarioSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2SegundoHorarioSemanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxSegundoDiaSemana, 0, 206, Short.MAX_VALUE)
                    .addComponent(jTextField2SegundoHorarioSemana))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSegundoDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2SegundoHorarioSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jRadioButtonSim)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonNao))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSim)
                    .addComponent(jRadioButtonNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton1_criar_turma)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_cancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1_Dia_semana, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox3_modalidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1Nome_turma)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1Nome_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1_Dia_semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3_modalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_criar_turma)
                    .addComponent(jButton2_cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1Nome_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1Nome_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1Nome_turmaActionPerformed

    private void jButton1_criar_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_criar_turmaActionPerformed
        // Criacao de turma
        DivTurmasDAO dao = new DivTurmasDAO();
        DivTurmas dt = new DivTurmas();
        
        String nome = jTextField1Nome_turma.getText(); 
        dt.setNome_turma(nome);
        
        dt.setDia_semana(CriaTurmaClass_dia_semana);
        
        if(CriarTurmaClass_horario != null){
        
            try {  
                
                dt.setHorario_dia(dt.formatarHora(CriarTurmaClass_horario));
                
            } catch (ParseException ex) {
                Logger.getLogger(CriarTurmaGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else if(jTextField2_horario.getText() != null){
        
            try {
                
                dt.setHorario_dia(dt.formatarHora(jTextField2_horario.getText()));
                
            } catch (ParseException ex) {
                Logger.getLogger(CriarTurmaGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else{
        JOptionPane.showMessageDialog(null,"Escolha um horário para criar a Turma. "
        + "Você pode digite a hora ou escolher no campo de seleção.");
        }

        dt.setModalidade(CriarTurmaClass_modalidade); 
        
        //-----------------------------------------------------------------------------------
        
        //depois da pergunta:
        
        //if que eu usei: --> \/
        
        /*if(campo1 e campo2 ou campo3 foram preenchidos{
            if(campo4 e campo5 foram preenchidos){
                    insere tudo no banco
            }else{
                    insere apenas os primeiros campos
            }
        }*/
        
        if(jComboBox1_Dia_semana.getSelectedItem() != null && jTextField2_horario.getText() != null || jComboBox2_horario.getSelectedItem() != null){
        //se os primeiros campos nao foram preenchidos, ele nao deixa criar os segundo dia e horario da turma.
        
            
        
                if(jTextField2SegundoHorarioSemana.getText() != null && CriaTurmaClassSegundo_dia_semana != null){
                    
                    dt.setSegudoDia_semana(CriaTurmaClassSegundo_dia_semana);
                    try {
                        dt.setSegundoHorario_dia(dt.formatarHora(jTextField2SegundoHorarioSemana.getText()));
                    } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(null,"Escolha algum horário nos campos de ''segundo horário''. ");
                    }
                    dao.insertCriaTurmaSegundoHorario(dt);
                    
                }else{
                
                    dao.insertCriaTurma(dt);
                    
                }
                
                /*if(jComboBox2SegundoHorarioSemana.getSelectedItem() != null && CriaTurmaClassSegundo_dia_semana != null){
                
                        dt.setSegudoDia_semana(CriaTurmaClassSegundo_dia_semana );
                    try {
                        dt.setSegundoHorario_dia(dt.formatarHora(CriarTurmaClassSegundo_horario));
                    } catch (ParseException ex) {
                        Logger.getLogger(CriarTurmaGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dao.insertCriaTurmaSegundoHorario(dt);
                    
                }*/
            
        }else{
        JOptionPane.showMessageDialog(null,"Escolha um primeiro dia da semana e um primeiro "
                                   + "horário da turma antes de criar um segundo dia da semana e um segundo horário. ");
        }
        
        
        //colocar um if aqui, dizendo que a pessoa nao pode criar um segundo horario para a turma 
        //caso ela nao tenha criado um primeiro horario da turma.
        
        
        
    }//GEN-LAST:event_jButton1_criar_turmaActionPerformed

    private void jComboBox1_Dia_semanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_Dia_semanaActionPerformed
        // TODO add your handling code here:
        
        
        if(jComboBox1_Dia_semana.getSelectedItem().equals("Segunda-feira")){
            
        CriaTurmaClass_dia_semana = "Segunda-feira";
        
        }else if(jComboBox1_Dia_semana.getSelectedItem().equals("Terça-feira")){
        CriaTurmaClass_dia_semana = "Terça-feira";
        
        }else if(jComboBox1_Dia_semana.getSelectedItem().equals("Quarta-feira")){
        CriaTurmaClass_dia_semana = "Quarta-feira";
        
        }else if(jComboBox1_Dia_semana.getSelectedItem().equals("Quinta-feira")){
        
        CriaTurmaClass_dia_semana = "Quinta-feira";
        }else if(jComboBox1_Dia_semana.getSelectedItem().equals("Sexta-feira")){
        
        CriaTurmaClass_dia_semana = "Sexta-feira";
        }else if(jComboBox1_Dia_semana.getSelectedItem().equals("Sábado")){
        
        CriaTurmaClass_dia_semana = "Sábado";
        }else {
        JOptionPane.showMessageDialog(null,"Escolha um campo na área de ''Dia da semana''. ");
        
        }
                
        
        
/*Segunda-feira
Terça-feira
Quarta-feira
Quinta-feira
Sexta-feira
Sábado
Domingo
*/
    }//GEN-LAST:event_jComboBox1_Dia_semanaActionPerformed

    private void jComboBox2_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_horarioActionPerformed
        // TODO add your handling code here:
        //DivTurmas dt = new DivTurmas();
        
        /*O item selecionado vai para a variavel, que vai para o metodo
        criarturma, que seta dentro da variavel que envia para dentro do banco de dados.*/
       
        
        //jComboBox2_horario
        
        
        if(jComboBox2_horario.getSelectedItem().equals("08:00")){
       
        CriarTurmaClass_horario = "08:00";

        }else if(jComboBox2_horario.getSelectedItem().equals("10:00")){
        CriarTurmaClass_horario = "10:00";
        
        }else if(jComboBox2_horario.getSelectedItem().equals("12:00")){
        CriarTurmaClass_horario = "12:00";
        
        }else if(jComboBox2_horario.getSelectedItem().equals("14:00")){
        CriarTurmaClass_horario = "14:00";
        
        }else if(jComboBox2_horario.getSelectedItem().equals("16:00")){
        CriarTurmaClass_horario = "16:00";
        
        }else if(jComboBox2_horario.getSelectedItem().equals("18:00")){
        CriarTurmaClass_horario = "18:00";
        
        }else if(jComboBox2_horario.getSelectedItem().equals("20:00")){
        CriarTurmaClass_horario = "20:00";
        }else {
        JOptionPane.showMessageDialog(null,"Escolha um horario para a turma.");
        }
        
       
    }//GEN-LAST:event_jComboBox2_horarioActionPerformed

    private void jComboBox3_modalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3_modalidadeActionPerformed
        // TODO add your handling code here:
        //CriarTurmaClass_modalidade
        
        if(jComboBox3_modalidade.getSelectedItem().equals("Inglês Básico")){
        CriarTurmaClass_modalidade = "Inglês Básico";

        }else if(jComboBox3_modalidade.getSelectedItem().equals("Inglês Intermediário")){
        CriarTurmaClass_modalidade = "Inglês Intermediário";
        }else if(jComboBox3_modalidade.getSelectedItem().equals("Inglês Avançado")){
        CriarTurmaClass_modalidade = "Inglês Avançado";
        }else if(jComboBox3_modalidade.getSelectedItem().equals("Inglês para Viagem")){
        CriarTurmaClass_modalidade = "Inglês para Viagem";
        }else if(jComboBox3_modalidade.getSelectedItem().equals("Inglês para Conversação")){
        CriarTurmaClass_modalidade = "Inglês para Conversação";
        }else{
        JOptionPane.showMessageDialog(null,"Escola uma modalidade");
        }
        
/*Inglês Básico
Inglês Intermediário
Inglês Avançado
Inglês para Viagem
Inglês para Conversação*/
        
    }//GEN-LAST:event_jComboBox3_modalidadeActionPerformed

    private void jButton2_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_cancelarActionPerformed
        // TODO add your handling code here:
        CriarTurmaGUI ctg = new CriarTurmaGUI();
        
       // Principal p = new Principal();
        
        
        //jDesktopPanePrincipal.add(p)
        
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar?",title, JOptionPane.YES_NO_OPTION);
          
        
        
          
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
            ctg.setVisible(false);
          
        }  else if (resposta == JOptionPane.NO_OPTION) {
            ctg.dispose();
            ctg.setVisible(true);
         
        }
       
       
        
    }//GEN-LAST:event_jButton2_cancelarActionPerformed

    private void jRadioButtonNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNaoActionPerformed
        // TODO add your handling code here:
        
        jComboBoxSegundoDiaSemana.setEnabled(false);
        jTextField2SegundoHorarioSemana.setEnabled(false);

  
        
    }//GEN-LAST:event_jRadioButtonNaoActionPerformed

    private void jRadioButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSimActionPerformed
        // TODO add your handling code here:
        
        //jRadioButtonSim
        /*Devemos chamar outro form ou parte deste mesmo form, para */
        jComboBoxSegundoDiaSemana.setEnabled(true);
        jTextField2SegundoHorarioSemana.setEnabled(true);

        

    }//GEN-LAST:event_jRadioButtonSimActionPerformed

    private void jTextField2_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_horarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_horarioActionPerformed

    private void jTextField2SegundoHorarioSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2SegundoHorarioSemanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2SegundoHorarioSemanaActionPerformed

    private void jComboBoxSegundoDiaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSegundoDiaSemanaActionPerformed
        // TODO add your handling code here:
        
        if(jComboBoxSegundoDiaSemana.getSelectedItem().equals("Segunda-feira")){
            
        CriaTurmaClassSegundo_dia_semana  = "Segunda-feira";
        
        }else if(jComboBoxSegundoDiaSemana.getSelectedItem().equals("Terça-feira")){
        CriaTurmaClassSegundo_dia_semana = "Terça-feira";
        
        }else if(jComboBoxSegundoDiaSemana.getSelectedItem().equals("Quarta-feira")){
        CriaTurmaClassSegundo_dia_semana = "Quarta-feira";
        
        }else if(jComboBoxSegundoDiaSemana.getSelectedItem().equals("Quinta-feira")){
        
        CriaTurmaClassSegundo_dia_semana = "Quinta-feira";
        }else if(jComboBoxSegundoDiaSemana.getSelectedItem().equals("Sexta-feira")){
        
        CriaTurmaClassSegundo_dia_semana = "Sexta-feira";
        }else if(jComboBoxSegundoDiaSemana.getSelectedItem().equals("Sábado")){
        
        CriaTurmaClassSegundo_dia_semana = "Sábado";
        }else {
        JOptionPane.showMessageDialog(null,"Escolha um campo na área de ''Dia da semana''. ");
        
        }
        
    }//GEN-LAST:event_jComboBoxSegundoDiaSemanaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_criar_turma;
    private javax.swing.JButton jButton2_cancelar;
    private javax.swing.JComboBox<String> jComboBox1_Dia_semana;
    private javax.swing.JComboBox<String> jComboBox2_horario;
    private javax.swing.JComboBox<String> jComboBox3_modalidade;
    private javax.swing.JComboBox<String> jComboBoxSegundoDiaSemana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JTextField jTextField1Nome_turma;
    private javax.swing.JTextField jTextField2SegundoHorarioSemana;
    private javax.swing.JTextField jTextField2_horario;
    // End of variables declaration//GEN-END:variables
}
