/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.etec.gui;

import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import br.gov.sp.etec.dao.AlunoDAO;
import br.gov.sp.etec.model.Aluno;
import br.gov.sp.etec.model.Endereco;
import br.gov.sp.etec.model.Globais;
import br.gov.sp.etec.model.Responsavel;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Edson
 */
public class CAlunoGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CAlunoGUI
     */
    public CAlunoGUI() {
        initComponents();

        jButtonResponsavel.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxModalidade = new javax.swing.JComboBox<>();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserA = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldRgA = new javax.swing.JFormattedTextField();
        jPanelEnderco = new javax.swing.JPanel();
        jTextFieldCep = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonResponsavel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBoxEstadoAluno = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldNomeR = new javax.swing.JTextField();
        jFormattedTextFieldCpfResp = new javax.swing.JFormattedTextField();
        jComboBoxSexoR = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldSobrenomeR = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jDateChooserR = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jFormattedTextFieldTelR = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelR = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanelEnderco1 = new javax.swing.JPanel();
        jTextFieldCepR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldCidadeR = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldRuaR = new javax.swing.JTextField();
        jTextFieldBairroR = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jTextFieldComplemento1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBoxEstadoResp = new javax.swing.JComboBox<>();
        jButtonSalvarR = new javax.swing.JButton();
        jButtonLimparR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Aluno");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(690, 580));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados pessoais:"));

        jLabel1.setText("Nome: ");

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel2.setText("Data de nascimento:");

        jLabel3.setText("Sexo:");

        jLabel4.setText("CPF:");

        jLabel9.setText("Modalidade:");

        jComboBoxModalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Itermediario", "Avançado", "EAD", "Conversação" }));

        jLabel10.setText("Sobrenome:");

        jDateChooserA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooserAFocusLost(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_refresh.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("RG:");

        try {
            jFormattedTextFieldRgA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooserA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldSobrenome))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jFormattedTextFieldRgA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldRgA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooserA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169))
        );

        jPanelEnderco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço :"));

        jLabel14.setText("CEP :");

        jLabel15.setText("Estado :");

        jLabel16.setText("Cidade :");

        jLabel17.setText("Rua :");

        jLabel18.setText("Bairro :");

        jLabel19.setText("Numero :");

        jLabel20.setText("Complemento :");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonResponsavel.setText("Responsável");
        jButtonResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResponsavelActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/placeholder (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxEstadoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        javax.swing.GroupLayout jPanelEndercoLayout = new javax.swing.GroupLayout(jPanelEnderco);
        jPanelEnderco.setLayout(jPanelEndercoLayout);
        jPanelEndercoLayout.setHorizontalGroup(
            jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndercoLayout.createSequentialGroup()
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEndercoLayout.createSequentialGroup()
                        .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndercoLayout.createSequentialGroup()
                                .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxEstadoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20)
                    .addGroup(jPanelEndercoLayout.createSequentialGroup()
                        .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelEndercoLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEndercoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonResponsavel)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEndercoLayout.setVerticalGroup(
            jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndercoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxEstadoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelEndercoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButtonResponsavel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsavel"));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados pessoais:"));

        jLabel33.setText("Nome: ");

        try {
            jFormattedTextFieldCpfResp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBoxSexoR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel34.setText("Data de nascimento:");

        jLabel35.setText("Sexo:");

        jLabel36.setText("CPF:");

        jLabel38.setText("Sobrenome:");

        jLabel7.setText("RG:");

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSexoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldSobrenomeR))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33)
                                .addComponent(jLabel36))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNomeR)
                                .addComponent(jFormattedTextFieldCpfResp, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldRg)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldNomeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextFieldSobrenomeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCpfResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jDateChooserR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jComboBoxSexoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato:"));

        try {
            jFormattedTextFieldTelR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCelR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel41.setText("Telefone");

        jLabel42.setText("Celular");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jFormattedTextFieldTelR)
                        .addComponent(jFormattedTextFieldCelR, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldTelR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldCelR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEnderco1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço :"));

        jLabel21.setText("CEP :");

        jLabel22.setText("Estado :");

        jLabel23.setText("Cidade :");

        jLabel24.setText("Rua :");

        jLabel25.setText("Bairro :");

        jLabel26.setText("Numero :");

        jLabel27.setText("Complemento :");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/placeholder (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxEstadoResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        javax.swing.GroupLayout jPanelEnderco1Layout = new javax.swing.GroupLayout(jPanelEnderco1);
        jPanelEnderco1.setLayout(jPanelEnderco1Layout);
        jPanelEnderco1Layout.setHorizontalGroup(
            jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderco1Layout.createSequentialGroup()
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderco1Layout.createSequentialGroup()
                        .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCidadeR, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBairroR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRuaR, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEnderco1Layout.createSequentialGroup()
                        .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnderco1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCepR, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxEstadoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEnderco1Layout.createSequentialGroup()
                        .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldComplemento1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEnderco1Layout.setVerticalGroup(
            jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderco1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldCepR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jComboBoxEstadoResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldCidadeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldRuaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldBairroR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldComplemento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSalvarR.setText("Salvar");
        jButtonSalvarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarRActionPerformed(evt);
            }
        });

        jButtonLimparR.setText("Limpar");
        jButtonLimparR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLimparR)
                            .addComponent(jButtonSalvarR)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelEnderco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelEnderco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonSalvarR)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimparR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato:"));

        try {
            jFormattedTextFieldTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldTelFocusGained(evt);
            }
        });

        try {
            jFormattedTextFieldCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Telefone");

        jLabel6.setText("Celular");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jFormattedTextFieldTel)
                        .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelEnderco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelEnderco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Aluno a = new Aluno();
        Date dataNasc = new Date();
        dataNasc = jDateChooserA.getDate();
        int age = a.calculaIdade(dataNasc);

        if (age < 18) {
            Object[] options = {"Sim", "Não"};
            int result = JOptionPane.showOptionDialog(null, "O aluno aparenta ser menor de idade, essa informação está correta?", "Informação correta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (result == 0) {
                jButtonResponsavel.setEnabled(true);
                jButtonSalvar.setEnabled(false);
            }
        } else {
            jButtonResponsavel.setEnabled(false);
            jButtonSalvar.setEnabled(true);
            setSize(700, 586);
        }

        Globais g = new Globais();
        String cpf = jFormattedTextFieldCpf.getText();
        String cpfR = cpf.replaceAll("[-.]", "");
        boolean cpfB = g.isCPF(cpfR);
        System.out.println(cpfB);
        if (cpfB == true) {
            jFormattedTextFieldCpf.setBackground(Color.white);
        } else {
            jFormattedTextFieldCpf.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "O campo CPF não é válido");
        }

        if (jTextFieldNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NOME do ALUNO está vazio, preencha-o");
        } else if (jTextFieldSobrenome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo SOBRENOME do ALUNO está vazio, preencha-o");
        } else if (jFormattedTextFieldCpf.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo CPF do ALUNO está vazio, preencha-o");
        } else if (jDateChooserA.getDateFormatString() == null) {
            JOptionPane.showMessageDialog(null, "O campo DATA DE NASCIMENTO do ALUNO está vazio, preencha-o");
        } else if (jFormattedTextFieldTel.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo TELEFONE do ALUNO está vazio, preencha-o");
        } else if (jFormattedTextFieldCel.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo CELULAR do ALUNO está vazio, preencha-o");
        } else if (jTextFieldCep.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CEP do ALUNO está vazio, preencha-o");
        } else if (jTextFieldCidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CIDADE do ALUNO está vazio, preencha-o");
        } else if (jTextFieldRua.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo RUA do ALUNO está vazio, preencha-o");
        } else if (jTextFieldBairro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo BAIRRO do ALUNO está vazio, preencha-o");
        } else if (jTextFieldNumero.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NÚMERO do ALUNO está vazio, preencha-o");
        }else if (age < 18) {
            JOptionPane.showMessageDialog(null, "Aluno menor de  idade...");
        } else {
            Object[] options = {"Sim", "Não"};
            int result = JOptionPane.showOptionDialog(null, "Tem certeza que deseja salvar os dados?", "Salvar dados?", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (result == 0) {
                AlunoDAO aDao = new AlunoDAO();
                aDao.insert(lerPessoais());
                aDao.insertEnd(lerEnd());
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            }
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResponsavelActionPerformed

        setSize(1340, 600);

    }//GEN-LAST:event_jButtonResponsavelActionPerformed

    private void jButtonSalvarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarRActionPerformed

        Globais g = new Globais();
        String cpf = jFormattedTextFieldCpf.getText();
        String cpfR = cpf.replaceAll("[-.]", "");
        boolean cpfB = g.isCPF(cpfR);
        if (cpfB == true) {
            jFormattedTextFieldCpf.setBackground(Color.white);
        } else {
            jFormattedTextFieldCpf.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "O campo CPF não é válido");
        }

        String cpf2 = jFormattedTextFieldCpfResp.getText();
        String cpfR2 = cpf2.replaceAll("[-.]", "");
        boolean cpfB2 = g.isCPF(cpfR2);
        System.out.println(cpfB2);
        if (cpfB2 == true) {
            jFormattedTextFieldCpfResp.setBackground(Color.white);
        } else {
            jFormattedTextFieldCpfResp.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "O campo CPF do responsável não é válido");
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        if (jTextFieldNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NOME do ALUNO está vazio, preencha-o");
        } else if (jTextFieldSobrenome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo SOBRENOME do ALUNO está vazio, preencha-o");
        } else if (jFormattedTextFieldCpf.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo CPF do ALUNO está vazio, preencha-o");
        } else if (jDateChooserA.getDateFormatString() == null) {
            JOptionPane.showMessageDialog(null, "O campo DATA DE NASCIMENTO do ALUNO está vazio, preencha-o");
        } else if (jFormattedTextFieldTel.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo TELEFONE do ALUNO está vazio, preencha-o");
        } else if (jFormattedTextFieldCel.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo CELULAR do ALUNO está vazio, preencha-o");
        } else if (jTextFieldCep.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CEP do ALUNO está vazio, preencha-o");
        } else if (jTextFieldCidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CIDADE do ALUNO está vazio, preencha-o");
        } else if (jTextFieldRua.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo RUA do ALUNO está vazio, preencha-o");
        } else if (jTextFieldBairro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo BAIRRO do ALUNO está vazio, preencha-o");
        } else if (jTextFieldNumero.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NÚMERO do ALUNO está vazio, preencha-o");
        } else if (jTextFieldNomeR.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NOME do RESPONSÁVEL está vazio, preencha-o");
        } else if (jTextFieldSobrenomeR.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo SOBRENOME do RESPONSÁVEL está vazio, preencha-o");
        } else if (jFormattedTextFieldCpfResp.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo CPF do RESPONSÁVEL está vazio, preencha-o");
        } else if (jDateChooserR.getDateFormatString() == null) {
            JOptionPane.showMessageDialog(null, "O campo DATA DE NASCIMENTO do RESPONSÁVEL está vazio, preencha-o");
        } else if (jFormattedTextFieldTelR.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo TELEFONE do RESPONSÁVEL está vazio, preencha-o");
        } else if (jFormattedTextFieldCelR.getValue() == null) {
            JOptionPane.showMessageDialog(null, "O campo CELULAR do RESPONSÁVEL está vazio, preencha-o");
        } else if (jTextFieldCepR.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CEP do RESPONSÁVEL está vazio, preencha-o");
        } else if (jTextFieldCidadeR.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CIDADE do RESPONSÁVEL está vazio, preencha-o");
        } else if (jTextFieldRuaR.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo RUA do RESPONSÁVEL está vazio, preencha-o");
        } else if (jTextFieldBairroR.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo BAIRRO do RESPONSÁVELestá vazio, preencha-o");
        } else if (jTextFieldNumero1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NÚMERO do RESPONSÁVEL está vazio, preencha-o");
        } else {
            Object[] options = {"Sim", "Não"};
            int result = JOptionPane.showOptionDialog(null, "Tem certeza que deseja salvar os dados?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (result == 0) {

                AlunoDAO aDao = new AlunoDAO();
                aDao.insertResponsavel(lerPessoaisR());
                aDao.insertEndResponsavel(lerEndR());
                aDao.insert(lerPessoais());
                aDao.insertEnd(lerEnd());
                /*responsavel*/
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            }
        }
    }//GEN-LAST:event_jButtonSalvarRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViaCEP via = new ViaCEP();

        try {
            via.buscar(jTextFieldCep.getText());
            jTextFieldRua.setText(via.getLogradouro());
            jTextFieldCidade.setText(via.getLocalidade());
            jComboBoxEstadoAluno.setSelectedItem(via.getUf());
            jTextFieldBairro.setText(via.getBairro());
        } catch (ViaCEPException ex) {
            JOptionPane.showMessageDialog(null, "Busca por CEP falhou, digite manualmente");
        }        //
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ViaCEP via = new ViaCEP();
        try {
            via.buscar(jTextFieldCepR.getText());
            jTextFieldRuaR.setText(via.getLogradouro());
            jTextFieldCidadeR.setText(via.getLocalidade());
            jComboBoxEstadoResp.setSelectedItem(via.getUf());
            jTextFieldBairroR.setText(via.getBairro());
        } catch (ViaCEPException ex) {
            JOptionPane.showMessageDialog(null, "Busca por CEP falhou, digite manualmente");
        }        //
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldNome.setText("");
        jTextFieldSobrenome.setText("");
        jFormattedTextFieldCpf.setText("");
//        jDateChooserA.setDateFormatString("");
        jTextFieldCep.setText("");
        jTextFieldCidade.setText("");
        jTextFieldRua.setText("");
        jTextFieldBairro.setText("");
        jTextFieldNumero.setText("");
        jTextFieldComplemento.setText("");
        jFormattedTextFieldTel.setText("");
        jFormattedTextFieldCel.setText("");

    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonLimparRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparRActionPerformed
        jTextFieldNomeR.setText("");
        jTextFieldSobrenomeR.setText("");
        jFormattedTextFieldCpfResp.setText("");
        jFormattedTextFieldRg.setText("");
//        jDateChooserR.setDateFormatString("");
        jTextFieldCepR.setText("");
        jTextFieldCidadeR.setText("");
        jTextFieldRuaR.setText("");
        jTextFieldBairroR.setText("");
        jTextFieldNumero1.setText("");
        jTextFieldComplemento1.setText("");
        jFormattedTextFieldTelR.setText("");
        jFormattedTextFieldCelR.setText("");
    }//GEN-LAST:event_jButtonLimparRActionPerformed

    private void jFormattedTextFieldTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelFocusGained

    }//GEN-LAST:event_jFormattedTextFieldTelFocusGained

    private void jDateChooserAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooserAFocusLost

    }//GEN-LAST:event_jDateChooserAFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Aluno a = new Aluno();
        Date dataNasc = new Date();
        dataNasc = jDateChooserA.getDate();
        int age = a.calculaIdade(dataNasc);

        if (age < 18) {

            jButtonResponsavel.setEnabled(true);
            jButtonSalvar.setEnabled(false);
        } else {
            jButtonResponsavel.setEnabled(false);
            jButtonSalvar.setEnabled(true);
            setSize(700, 590);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public Aluno lerPessoais() {
        Aluno a = new Aluno();
        String nome = jTextFieldNome.getText();
        String sobrenome = jTextFieldSobrenome.getText();
        String rgR = jFormattedTextFieldRgA.getText();
        String rg = rgR.replaceAll(".", "");
        String cpfR = jFormattedTextFieldCpf.getText();
        String cpf = cpfR.replaceAll("[. -]", "");
        //
        Date dataA = new Date();
        dataA = jDateChooserA.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String nasc = formatter.format(dataA);
        //
        String sexo = jComboBoxSexo.getSelectedItem().toString();
        String model = jComboBoxModalidade.getSelectedItem().toString();
        String telR = jFormattedTextFieldTel.getText();
        String tel = telR.replaceAll("[()-]", "");
        String celR = jFormattedTextFieldCel.getText();
        String cel = celR.replaceAll("[()-]", "");
        
        a.setRg(rg);
        a.setTel_fixo(tel);
        a.setTel_celular(cel);
        a.getRa();
        a.setNome(nome);
        a.setSobrenome(sobrenome);
        a.setCpf(cpf);
        a.setData_nasc(nasc);
        a.setSexo(sexo);
        a.setNivelI(model);

        return a;
    }

    public Endereco lerEnd() {
        Endereco e = new Endereco();
        String cepR = jTextFieldCep.getText();
        String cep = cepR.replaceAll("[-]", "");
        String estado = jComboBoxEstadoAluno.getSelectedItem().toString();
        String cidade = jTextFieldCidade.getText();
        String rua = jTextFieldRua.getText();
        String bairro = jTextFieldBairro.getText();
        String numero = jTextFieldNumero.getText();
        String comple = jTextFieldComplemento.getText();

        e.setCep(cep);
        e.setUf(estado);
        e.setCidade(cidade);
        e.setRua(rua);
        e.setBairro(bairro);
        e.setNumero(numero);
        e.setComplemento(comple);
        return e;

    }

    /*Responsavel*/
    public Endereco lerEndR() {
        Endereco e = new Endereco();
        String cep = jTextFieldCepR.getText();
        String estado = jComboBoxEstadoResp.getSelectedItem().toString();
        String cidade = jTextFieldCidadeR.getText();
        String rua = jTextFieldRuaR.getText();
        String bairro = jTextFieldBairroR.getText();
        String numero = jTextFieldNumero1.getText();
        String comple = jTextFieldComplemento1.getText();
        
        
        e.setCep(cep);
        e.setUf(estado);
        e.setCidade(cidade);
        e.setRua(rua);
        e.setBairro(bairro);
        e.setNumero(numero);
        e.setComplemento(comple);
        return e;

    }

    public Responsavel lerPessoaisR() {
        Responsavel res = new Responsavel();
        String nome = jTextFieldNomeR.getText();
        String sobrenome = jTextFieldSobrenomeR.getText();
        String cpfR = jFormattedTextFieldCpfResp.getText();
        String cpf = cpfR.replaceAll("[. -]", "");
        System.out.print(cpf);
        String rgR = jFormattedTextFieldRg.getText();
        String rg = rgR.replaceAll("[. -]", "");
        Date dataR = new Date();
        dataR = jDateChooserR.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String nasc = formatter.format(dataR);
        String sexo = jComboBoxSexoR.getSelectedItem().toString();
        String telR = jFormattedTextFieldTelR.getText();
        String tel = telR.replaceAll("[()-]", "");
        String celR = jFormattedTextFieldCelR.getText();
        String cel = celR.replaceAll("[()-]", "");
        
        res.setNome(nome);
        res.setSobrenome(sobrenome);
        res.setCpf(cpf);
        res.setRg(rg);
        res.setDt_nasc(nasc);
        res.setSexo(sexo);
        res.setTel_fixo(tel);
        res.setTel_celular(cel);

        return res;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLimparR;
    private javax.swing.JButton jButtonResponsavel;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSalvarR;
    private javax.swing.JComboBox<String> jComboBoxEstadoAluno;
    private javax.swing.JComboBox<String> jComboBoxEstadoResp;
    private javax.swing.JComboBox<String> jComboBoxModalidade;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxSexoR;
    private com.toedter.calendar.JDateChooser jDateChooserA;
    private com.toedter.calendar.JDateChooser jDateChooserR;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelR;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfResp;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldRgA;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelEnderco;
    private javax.swing.JPanel jPanelEnderco1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBairroR;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCepR;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCidadeR;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldComplemento1;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeR;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldRuaR;
    private javax.swing.JTextField jTextFieldSobrenome;
    private javax.swing.JTextField jTextFieldSobrenomeR;
    // End of variables declaration//GEN-END:variables
}
