/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.etec.gui;

import br.gov.sp.etec.dao.CadastroAtivoDAO;
import br.gov.sp.etec.dao.CadastroPassivoDAO;
import br.gov.sp.etec.dao.CategoriaDAO;
import br.gov.sp.etec.model.CadastroContas;
import br.gov.sp.etec.model.Categoria;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author ext
 */
public class FCadastrarContas extends javax.swing.JInternalFrame {
    String var;
    /**
     * Creates new form NewJInternalFrame
     */
    public FCadastrarContas() {
        initComponents();
      
        Date data = new Date();
        jDateChooser1.setDate(data);
        
        
//        ArrayList<Object> array;
//        jComboBoxContas.addItem(array);
               
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxContas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipos = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastro de contas");

        jLabel1.setText("Descrição:");

        jLabel2.setText("Valor:");

        jLabel3.setText("Data");

        jLabel4.setText("Categoria:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Passivo", " " }));
        jComboBoxCategoria.setToolTipText("");
        jComboBoxCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxCategoriaFocusLost(evt);
            }
        });
        jComboBoxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCategoriaMouseClicked(evt);
            }
        });

        jButton1.setText("Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Contas:");

        jComboBoxContas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxContasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxContasFocusLost(evt);
            }
        });
        jComboBoxContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxContasMouseClicked(evt);
            }
        });

        jLabel6.setText("Tipos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldValor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxContas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        CadastroAtivoDAO dao = new CadastroAtivoDAO();
        if(var.equals("Ativo")){
//        Categoria c = (Categoria) jComboBoxContas.getSelectedItem();
        //
        CadastroContas cadastro = new CadastroContas();
        //
        String descricao = jTextFieldDesc.getText();
        cadastro.setDescricaoA(descricao);
        
        String valor = jTextFieldValor.getText();
        Scanner testeValor = new Scanner(valor);
        if(testeValor.hasNextDouble()){
            cadastro.setValor(testeValor.nextDouble());
        }
        
        Date data = jDateChooser1.getDate();
        DateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
        String dataFormatada = formatter.format(data);
        cadastro.setData_lancamento(dataFormatada);
        
       
        if(jComboBoxTipos.getItemCount() == 0){
                cadastro.setCategoria(jComboBoxContas.getSelectedItem().toString());
                
        } else{
                cadastro.setCategoria(jComboBoxContas.getSelectedItem().toString());
                cadastro.setSubcategoria(jComboBoxTipos.getSelectedItem().toString());
        }
        dao.insert(cadastro);
        
        
        } else{
            CadastroPassivoDAO pdao = new CadastroPassivoDAO();
//            Categoria c = (Categoria) jComboBoxContas.getSelectedItem();
        //
        CadastroContas cadastro = new CadastroContas();
        
        //
        String descricao = jTextFieldDesc.getText();
        cadastro.setDescricaoA(descricao);
        
        String valor = jTextFieldValor.getText();
        Scanner testeValor = new Scanner(valor);
        if(testeValor.hasNextDouble()){
            cadastro.setValor(testeValor.nextDouble());
        }
        
        Date data = jDateChooser1.getDate();
        DateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
        String dataFormatada = formatter.format(data);
        cadastro.setData_lancamento(dataFormatada);
        
        if(jComboBoxTipos.getItemCount() == 0){
                cadastro.setCategoria(jComboBoxContas.getSelectedItem().toString());

        } else{
                cadastro.setCategoria(jComboBoxContas.getSelectedItem().toString());
                cadastro.setSubcategoria(jComboBoxTipos.getSelectedItem().toString());
        }
        pdao.insert(cadastro);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaFocusLost
        CategoriaDAO cdao = new CategoriaDAO();
        
        var = jComboBoxCategoria.getSelectedItem().toString();
        if(var.equals("Ativo")){
            jComboBoxContas.removeAllItems();
        for(Categoria cat: cdao.selectAtivo()){
            jComboBoxContas.addItem(cat);}
        }
        else{
            jComboBoxContas.removeAllItems();
        for(Categoria cat: cdao.selectPassivo()){
            jComboBoxContas.addItem(cat);}
        }
    }//GEN-LAST:event_jComboBoxCategoriaFocusLost

    private void jComboBoxCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaFocusGained

    private void jComboBoxCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaMouseClicked

            }//GEN-LAST:event_jComboBoxCategoriaMouseClicked

    private void jComboBoxContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxContasMouseClicked
                                                       

    }//GEN-LAST:event_jComboBoxContasMouseClicked

    private void jComboBoxContasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxContasFocusLost
        String var1 = jComboBoxContas.getSelectedItem().toString();
        if(var1.equals("Clientes")){
            jComboBoxTipos.removeAllItems();
        for(Object array1 : AtivoClientes()){
            jComboBoxTipos.addItem(array1);}
        }
        else if(var1.equals("Estoques")){
            jComboBoxTipos.removeAllItems();
        for(Object array2: AtivoEstoques()){
            jComboBoxTipos.addItem(array2);}
        }
        else if(var1.equals("Adiantamento")){
            jComboBoxTipos.removeAllItems();
        for(Object array2: AtivoAdiantamentos()){
            jComboBoxTipos.addItem(array2);}
        }
        else if(var1.equals("Imobilizados")){
            jComboBoxTipos.removeAllItems();
        for(Object array2: AtivoImobilizados()){
            jComboBoxTipos.addItem(array2);}
        }
        else if(var1.equals("Contas a pagar")){
            jComboBoxTipos.removeAllItems();
        for(Object array2: PassivoContasPagar()){
            jComboBoxTipos.addItem(array2);}
        }
        else if(var1.equals("Contas a pagar")){
            jComboBoxTipos.removeAllItems();
        for(Object array2: PassivoContasPagar()){
            jComboBoxTipos.addItem(array2);}
        }
        else if(var1.equals("Patrimônio Líquido")){
            jComboBoxTipos.removeAllItems();
        for(Object array2: PassivoPatrimonioLiquido()){
            jComboBoxTipos.addItem(array2);}
        } 
        else{
            JOptionPane.showMessageDialog(null, "Não possui subcategoria");
            jComboBoxTipos.removeAllItems();
        }
    }//GEN-LAST:event_jComboBoxContasFocusLost

    private void jComboBoxContasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxContasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxContasFocusGained
    
    
     
     public ArrayList<Object> AtivoClientes() {
        ArrayList<Object> array = new ArrayList();
        array.add("EAD");
        array.add("Avulso");
        array.add("Mensal");
        return array;
    }
     
      public ArrayList<Object> AtivoEstoques() {
        ArrayList<Object> array = new ArrayList();
        array.add("Material de consumo");
        return array;
    }
     
      public ArrayList<Object> AtivoAdiantamentos() {
        ArrayList<Object> array = new ArrayList();
        array.add("Adiantamento de lucros");
        return array;
    }
      
        public ArrayList<Object> AtivoImobilizados() {
        ArrayList<Object> array = new ArrayList();
        array.add("Máquinas e equipamentos");
        array.add("Móveis e Utensílios");
        return array;
    }
    public ArrayList<Object> PassivoContasPagar() {
        ArrayList<Object> array = new ArrayList();
        array.add("Água");
        array.add("Luz");
        array.add("Telefone");
        array.add("Aluguel");
        array.add("Internet");
        return array;
    }
    
    public ArrayList<Object> PassivoPatrimonioLiquido() {
        ArrayList<Object> array = new ArrayList();
        array.add("Capital social");
        array.add("Distribuição de lucros");
        array.add("Reserva de capital");
       
        return array;
    }
    
        
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Object> jComboBoxCategoria;
    private javax.swing.JComboBox<Object> jComboBoxContas;
    private javax.swing.JComboBox<Object> jComboBoxTipos;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
